### ISSUE TITLE
The client application is not known or is not authorized

### ISSUE THREAD

**Issue by RickwangF** [scottbrady91/IdentityServer3-Example-Clients#1]
When I setting up my hybridflow Client application to authenticate , I getting the error.
The server side and client side code is same as the post.
The only difference with source code is that I separate client code into two solutions.I think it's not a big deal.

form-post client code is perfectly run in my laptop.

This is my RequestURL
https://localhost:44302/core/connect/authorize?client_id=hybridclient&redirect_uri=https%3a%2f%2flocalhost%3a44304&response_mode=form_post&response_type=code+id_token+token&scope=openid+profile+email+roles+offline_access&state=OpenIdConnect.AuthenticationProperties%3dvc9byU9ziC0tPK0QKLbFyfuTwnWRFP0PAEoek4TZeJ6GvPZHNZjryimU7CJrpIzM0uegt0j_76uZanAu2OOV8S_lxMRJz6N1YzXi3rZO_n3c1lnhczkLcq6mKc2L4eeryWMgujS-ptKBaBoSpZPXCpiP7zPpvjs-LwfeQt9otmH2HuG0bJ1klC2pStk-AlAO2RK1YmfrJk2U8pcL4Rd5JQ&nonce=636183388691732722.MzVhMTMxOTUtMDE5Ny00OWI5LWJmZTItMjg5ODQ2MDBkNzZkZTU1NzQ0ZjItZDU3ZS00MmU4LWI4NzQtZTQ5ZTc0MTZiNzBl

Please tell me where I am wrong

**Comment by scottbrady91** [comment]
What is the error? Look in the IdentityServer logs, that will most probably tell you what is wrong: https://identityserver.github.io/Documentation/docsv2/configuration/logging.html
